app/dashboard/urls.py
from django.urls import path
from dashboard import views

from .views import *
app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

app/superstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
]

app/dashboard/models.py
from django.db import models

# Create your models here.
class Superstore(models.Model):
    order_id = models.CharField(max_length=50)
    order_date = models.DateField()
    ship_date = models.DateField()
    ship_mode = models.CharField(max_length=50)
    customer_id = models.CharField(max_length=50)
    customer_name = models.CharField(max_length=50)
    segment = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    postal_code = models.IntegerField()
    region	= models.CharField(max_length=50)
    product_id = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    sub_category  = models.CharField(max_length=50)
    product_name  = models.CharField(max_length=150)
    sales  = models.FloatField()
    quantity  = models.IntegerField()
    discount  = models.FloatField()
    profit = models.FloatField()
    

app/dashboard/views.py
from django.core.checks import messages
from django.db.models.aggregates import Min
from django.db.models.expressions import Value
from django.shortcuts import render
from .models import Superstore
from django.db.models import Sum, Count, FloatField,Max, Func
from django.db import models
from django.db.models.functions import ExtractYear, ExtractMonth
import pandas as pd

class Year(Func):
    function = 'EXTRACT'
    template = '%(function)s(YEAR from %(expressions)s)'
    output_field = models.IntegerField()

def home(request):
    return render(request, 'index.html')

def dashboard(request):
    
    year = request.GET.get('year')

    sale = Superstore.objects
    profit = Superstore.objects
    order = Superstore.objects
    profitmargin = Superstore.objects
    furnituresales = Superstore.objects
    Officesales = Superstore.objects
    technologysales = Superstore.objects
    furnitureprofit = Superstore.objects
    technologyprofit = Superstore.objects
    Officeprofit = Superstore.objects
    years = Superstore.objects.annotate(year=ExtractYear('ship_date')).values('year').annotate(cyear=Count('year')).values('year')

    if (year):
        message = 'Sale Report Jan 1, '+year+' - Dec 31, '+year
        sale = sale.filter(ship_date__year=year)
        profit = profit.filter(ship_date__year=year)
        order = order.filter(ship_date__year=year)
        profitmargin = profitmargin.filter(ship_date__year=year)
        furnituresales = furnituresales.filter(category='Furniture',ship_date__year=year)
        Officesales = Officesales.filter(category='Office Supplies',ship_date__year=year)
        technologysales = technologysales.filter(category='Technology',ship_date__year=year)
        furnitureprofit =furnitureprofit.filter(category='Furniture',ship_date__year=year)
        technologyprofit = technologyprofit.filter(category='Technology',ship_date__year=year)
        Officeprofit = Officeprofit.filter(category='Office Supplies',ship_date__year=year)
        sale_summary = list()
        for m in range(12):
            totalSale = sale.filter(ship_date__month=(m+1)).annotate(month=ExtractMonth('ship_date')).values('month').annotate(cmonth=Count('month')).aggregate(Sum('sales'))
            if totalSale['sales__sum'] is not None:
                sale_summary.append(totalSale['sales__sum'])
            else:
                sale_summary.append(0)
        graph_labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Otc', 'Nov', 'Dec']
        graph_values = sale_summary
    else:
        start_year = years.order_by('year').first()
        end_year = years.order_by('year').last()
        message = 'Sale Report Jan 1, '+str(start_year['year'])+' - Dec 31, '+str(end_year['year'])
        sale_summary = sale.annotate(year=ExtractYear('ship_date')).values('year').annotate(totlaSale=Sum('sales')).order_by('year')
        graph_labels = sale_summary.values_list('year', flat=True)
        graph_values = sale_summary.values_list('totlaSale', flat=True)
    
    sale = sale.aggregate(Sum('sales'))
    profit = profit.aggregate(Sum('profit'))
    order = order.values('order_id').distinct().count()
    profitmargin = profitmargin.aggregate(price_diff=(Sum('profit') / Sum('sales'))*100)
    furnituresales = furnituresales.aggregate(Sum('sales'))
    Officesales = Officesales.aggregate(Sum('sales'))
    technologysales = technologysales.aggregate(Sum('sales'))
    furnitureprofit = furnitureprofit.aggregate(Sum('profit'))
    technologyprofit = technologyprofit.aggregate(Sum('profit'))
    Officeprofit = Officeprofit.aggregate(Sum('profit'))

    filter_years = years.order_by('-year').values_list('year', flat=True)
    context = {
        'message':message,
        'sale':sale,
        'profit':profit,
        'order':order,
        'profitmargin':profitmargin,
        'furnituresales':furnituresales,
        'Officesales':Officesales,
        'technologysales':technologysales,
        'furnitureprofit':furnitureprofit,
        'Officeprofit':Officeprofit,
        'technologyprofit':technologyprofit,
        'filter_years':list(filter_years),
        'graph_labels':list(graph_labels),
        'graph_values':list(graph_values),
        'year':year
        }
    return render(request, "dashboard.html" ,context)

app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superstore</title>
    <link rel="stylesheet" href="{% static 'indexstyle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-light bg-light py-0">
        <div class="container mt-0">
            <!--logo-->
            <a class="navbar-brand" href="{% url 'dashboard:home' %}">
                <img src="{% static 'img/superstore-logo.svg' %}" alt="" width="172" height="35">
            </a>
            <!--menu-->
            <div class="navbar-nav d-flex flex-row">
                <a class="nav-link active text-primary px-2 " aria-current="page" href="{% url 'dashboard:home' %}">Home</a>
                <a class="nav-link px-2" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
            </div>
        </div>
    </nav>

    <header class="header">
        <div class="container">
            <div class="header-area">
                <h1 class="display-1 text-white">Welcome to Superstore Dashboard</h1>
                <p class="lead text-white">Office Supplies, Furniture and Technology </p>
                <a class="btn btn-primary btn-lg mt-4 " href="{% url 'dashboard:dashboard' %}" role="button">Go to Dashboard</a>
            </div>
        </div>
    </header>
    <!--Footer-->
    <footer class="container text-center mb-3 border-top">
        <small class="text-center text-secondary">
            Copyright © Superstore Company 2021. All rights reserved.
        </small>
    </footer> 

    
</body>
</html>